// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $album_id_ from "./routes/album/[id].tsx";
import * as $band_id_ from "./routes/band/[id].tsx";
import * as $book_id_ from "./routes/book/[id].tsx";
import * as $event_id_ from "./routes/event/[id].tsx";
import * as $heraldry_id_ from "./routes/heraldry/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $organization_id_ from "./routes/organization/[id].tsx";
import * as $person_id_ from "./routes/person/[id].tsx";
import * as $song_id_ from "./routes/song/[id].tsx";
import * as $writer_id_ from "./routes/writer/[id].tsx";
import * as $DateForm from "./islands/DateForm.tsx";
import * as $Events from "./islands/Events.tsx";
import * as $Heraldries from "./islands/Heraldries.tsx";
import * as $NameForm from "./islands/NameForm.tsx";
import * as $Organizations from "./islands/Organizations.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/album/[id].tsx": $album_id_,
    "./routes/band/[id].tsx": $band_id_,
    "./routes/book/[id].tsx": $book_id_,
    "./routes/event/[id].tsx": $event_id_,
    "./routes/heraldry/[id].tsx": $heraldry_id_,
    "./routes/index.tsx": $index,
    "./routes/organization/[id].tsx": $organization_id_,
    "./routes/person/[id].tsx": $person_id_,
    "./routes/song/[id].tsx": $song_id_,
    "./routes/writer/[id].tsx": $writer_id_,
  },
  islands: {
    "./islands/DateForm.tsx": $DateForm,
    "./islands/Events.tsx": $Events,
    "./islands/Heraldries.tsx": $Heraldries,
    "./islands/NameForm.tsx": $NameForm,
    "./islands/Organizations.tsx": $Organizations,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
